server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


spring:
  application:
    name: discovery-server
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0

  security:
    user:
      name: eureka
      password: password
      basic:
        enabled: true





